# Generated by Django 3.1.3 on 2020-11-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0004_auto_20201103_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='carga_horaria',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='Auditório FACET', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='tema',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='website',
            field=models.CharField(default='www.faculdadedetimbauba.edu.br', max_length=200),
        ),
    ]
