# Generated by Django 3.1.3 on 2020-11-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0005_auto_20201108_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestrante',
            name='titulacao',
            field=models.CharField(default='Mestre', max_length=100),
        ),
    ]
