# Generated by Django 3.1.3 on 2020-11-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0006_palestrante_titulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(default='Secretaria', max_length=100),
        ),
    ]
